version: '3.8'

services:
  # データベース: MySQL
  db:
    image: mysql:8.0
    container_name: simple_blog_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: simple_blog_development
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - blog_network

  # アプリケーション: Ruby on Rails
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple_blog_app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: blog_user
      DATABASE_PASSWORD: blog_password
      RAILS_ENV: development
    networks:
      - blog_network
    stdin_open: true
    tty: true

  # Webサーバー: nginx
  nginx:
    image: nginx:latest
    container_name: simple_blog_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/app/public:ro
    depends_on:
      - app
    networks:
      - blog_network

volumes:
  mysql_data:
  bundle_cache:

networks:
  blog_network:
    driver: bridge
